### ISSUE TITLE
Pipeline error!

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/snacc#80]
Most recent commit has broken our pipeline.

Traceback (most recent call last):
  File "/home/alex/anaconda3/bin/snacc", line 11, in <module>
    load_entry_point('snacc', 'console_scripts', 'snacc')()
  File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/home/alex/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alex/Documents/bioncd-hackseq/snacc/cli.py", line 88, in <module>
    help="Whether to automatically open the log in the browser if log type is html. Defaults to True.")
  File "/home/alex/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/home/alex/anaconda3/lib/python3.7/site-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)

**Comment by SweetiePi** [comment]
That's the full traceback. Did we remove -d and -f as command line arguments?

**Comment by Benjamin-Lee** [comment]
They should still be usable, just deprecated. You should now be able to pass in directories and files directly to snacc, but it should work either way.

**Comment by Benjamin-Lee** [comment]
Can you send the exact command you used to generate the issue?

**Comment by SweetiePi** [comment]
From snacc home directory:
`snacc -d ../test_dataset/ -o lzma_test.csv`

**Comment by Benjamin-Lee** [comment]
Well, two things: I'm not getting an error but it isn't working with `-d` and second, it does work when you just pass the dataset without the flag:

`snacc ../test_dataset/ -o lzma_test.csv`

Will get on fix, but for now, just make sure to do a `pip install -e .` in the main directory and omit the `-d` flag

**Comment by SweetiePi** [comment]
Thanks!

I'm still getting the error even with omitting the -d flag. It might be an Anaconda issue.

**Comment by Benjamin-Lee** [comment]
Fixed. See #81.

**Comment by SweetiePi** [comment]
Unfortunately I'm still getting the same error. I'll try running it on a Conda-free environment to see if that's the issue.

For now, reverting back to e90c26bf5f50f9e2e083cdb657c4967851b61365 allows it to work.

**Comment by Benjamin-Lee** [comment]
Let me know if the newest version works without Conda - the newest version is running fine for me

**Comment by Benjamin-Lee** [comment]
```
(env) Benjamins-MacBook-Pro-9:snacc BenjaminLee$ snacc -d ../test_dataset/ -o lzma_test.csv
Warning: the -f and -d flags are deprecated and will be removed before release. Please pass files and paths directly witho
ut the flags.
Compressing individual files...
  0%|                                                                                               | 0/9 [00:00<?, ?it/s]
```

**Comment by souravsingh** [comment]
This means we might need to pin a minimum version for click to make the project work.
